{{- if .Values.reth.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "adi-stack.fullname" . }}-reth
  labels:
    {{- include "adi-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: reth
  {{- with (include "adi-stack.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "adi-stack.fullname" . }}-reth
  replicas: {{ .Values.reth.replicaCount }}
  selector:
    matchLabels:
      {{- include "adi-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: reth
  template:
    metadata:
      labels:
        {{- include "adi-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: reth
      annotations:
        {{- include "adi-stack.podAnnotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "adi-stack.serviceAccountName" . }}
      {{- include "adi-stack.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if not .Values.openshift.enabled }}
      securityContext:
        {{- toYaml .Values.reth.podSecurityContext | nindent 8 }}
      {{- else }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      {{- end }}
      initContainers:
        - name: init-directories
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              mkdir -p /data/db /data/static_files
              chown -R 1000:1000 /data
              chmod -R 775 /data
          volumeMounts:
            - name: data
              mountPath: /data
          {{- if not .Values.openshift.enabled }}
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
          {{- end }}
      containers:
        - name: reth
          image: {{ include "adi-stack.reth.image" . }}
          imagePullPolicy: {{ .Values.reth.image.pullPolicy }}
          {{- if not .Values.openshift.enabled }}
          securityContext:
            {{- toYaml .Values.reth.containerSecurityContext | nindent 12 }}
          {{- else }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          {{- end }}
          args:
            - node
            - --datadir=/data
            - --log.file.directory=/tmp
            - --chain={{ .Values.reth.chain }}
            - --http
            - --http.addr=0.0.0.0
            - --http.port={{ .Values.reth.httpPort }}
            - --http.api={{ .Values.reth.httpApi }}
            {{- if .Values.reth.metricsEnabled }}
            - --metrics=0.0.0.0:{{ .Values.reth.metricsPort }}
            {{- end }}
            - --port={{ .Values.reth.p2pPort }}
            - --discovery.addr=0.0.0.0
            {{- if .Values.reth.nat }}
            - --nat={{ .Values.reth.nat }}
            {{- end }}
            {{- if and (eq .Values.reth.syncMode "checkpoint") .Values.reth.checkpointUrl }}
            - --debug.tip={{ .Values.reth.checkpointUrl }}
            {{- end }}
            {{- range .Values.reth.bootnodes }}
            - --bootnodes={{ . }}
            {{- end }}
            {{- range .Values.reth.extraArgs }}
            - {{ . }}
            {{- end }}
          ports:
            - name: http-rpc
              containerPort: {{ .Values.reth.httpPort }}
              protocol: TCP
            - name: p2p-tcp
              containerPort: {{ .Values.reth.p2pPort }}
              protocol: TCP
            - name: p2p-udp
              containerPort: {{ .Values.reth.p2pPort }}
              protocol: UDP
            {{- if .Values.reth.metricsEnabled }}
            - name: metrics
              containerPort: {{ .Values.reth.metricsPort }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: http-rpc
            initialDelaySeconds: {{ .Values.reth.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.reth.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.reth.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.reth.livenessProbe.failureThreshold }}
          readinessProbe:
            tcpSocket:
              port: http-rpc
            initialDelaySeconds: {{ .Values.reth.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.reth.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.reth.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.reth.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.reth.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.reth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.reth.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.reth.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "adi-stack.labels" . | nindent 10 }}
          app.kubernetes.io/component: reth
          {{- with .Values.reth.persistence.labels }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.reth.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.reth.persistence.accessMode }}
        {{- if .Values.reth.persistence.storageClass }}
        storageClassName: {{ .Values.reth.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.reth.persistence.size }}
{{- end }}
